name: Chu-Cheng Lin
description: Personal website
menu:
 - page: About
   url: /about
 - page: Papers
   url: /papers
   links:
    - title: Working papers
      url: "#working-papers"
    - title: Published papers
      url: "#published-papers"
mathjax: true
markdown: kramdown
encoding: utf-8
baseurl: kitsing.github.io
locale: en_GB
